### ISSUE TITLE
Cannot run "user" block

### ISSUE THREAD

**Issue by cifkao** [udapi/udapi-python#44]
It doesn't seem possible to run a block which is not inside `udapi.block`. I tried `udapy .myblock.MyBlock` with myblock.py in the working directory, but I get the following error:
```
2018-02-07 14:27:40,281 [WARNING] _import_blocks - Error when trying import the block .myblock.MyBlock
Traceback (most recent call last):
  File "/a/merkur3/cifka/miniconda3/envs/py35_tf_cpu/bin/udapy", line 84, in <module>
    runner.execute()
  File "/a/merkur3/cifka/miniconda3/envs/py35_tf_cpu/lib/python3.5/site-packages/udapi/core/run.py", line 133, in execute
    blocks = _import_blocks(block_names, block_args)
  File "/a/merkur3/cifka/miniconda3/envs/py35_tf_cpu/lib/python3.5/site-packages/udapi/core/run.py", line 94, in _import_blocks
    exec(command)  # pylint: disable=exec-used
  File "<string>", line 1, in <module>
ImportError: No module named 'myblock'
```

**Comment by martinpopel** [comment]
Try just `udapy .MyBlock` xor move the file to `./myblock/myblock.py`.
If it works, please send a PR with improved documentation, I know it is lacking. Thanks

**Comment by cifkao** [comment]
Thanks. That gave me the same error, but `PYTHONPATH="$PWD" udapy .MyBlock` works.
Not sure whether that should be added to the docs, and where.

**Comment by martinpopel** [comment]
Yes, if the `udapy` script should be called from any directory, the path to the user blocks (`myblock.py`) should be included in the PYTHONPATH. See https://docs.python.org/3/library/sys.html#sys.path
