### ISSUE TITLE
how to supress color for copy?

### ISSUE THREAD

**Issue by arademaker** [udapi/udapi-python#89]
```
% cat *.conllu | udapy -N -q util.Eval node='if node.lemma == "ao": node.parent.parent.draw()'| pbcopy
Traceback (most recent call last):
  File "/Users/ar/work/udapi-python/bin/udapy", line 114, in <module>
    runner.execute()
  File "/Users/ar/work/udapi-python/udapi/core/run.py", line 133, in execute
    blocks = _import_blocks(block_names, block_args)
  File "/Users/ar/work/udapi-python/udapi/core/run.py", line 103, in _import_blocks
    new_block_instance = eval(command)  # pylint: disable=eval-used
  File "<string>", line 1, in <module>
  File "/Users/ar/work/udapi-python/udapi/block/util/eval.py", line 33, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'color'
```

**Comment by martinpopel** [comment]
`udapy -q util.Eval node='if node.lemma == "ao": node.parent.parent.draw(color=0)`

Explanation:
* `udapy -T` is a shortcut for adding `write.TextModeTrees color=1` to the end of the scenario
* `udapy -N` is a shortcut for adding `color=0` to the end of the scenario (so that it overrides `color=1`)
*  So `-N` can be used only with `-T`. Block `util.Eval` has no parameter `color`.
*  see `udapy -h`
